services:
  - type: web
    name: legal-contract-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: BACKEND_URL
        value: https://legal-contract-backend.onrender.com  # optional

  - type: web
    name: legal-contract-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm start
    # staticPublishPath: frontend/out  # only if using `next export` or static deploy
